# Generated by Django 4.0.3 on 2023-04-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddField(
            model_name='paper',
            name='json_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='原始json'),
        ),
        migrations.AddField(
            model_name='paper',
            name='li_authors',
            field=models.ManyToManyField(to='science.scholar'),
        ),
        migrations.AddField(
            model_name='paper',
            name='li_keywords',
            field=models.ManyToManyField(to='science.keywords'),
        ),
        migrations.AddField(
            model_name='paper',
            name='periodical',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='期刊名称'),
        ),
        migrations.AddField(
            model_name='paper',
            name='sno',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sno'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='id_from_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='网站id'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='json_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='原始json'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='机构'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='organization_02',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='机构2'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='organization_03',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='机构3'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='项目'),
        ),
    ]
