# Generated by Django 4.0.3 on 2023-04-26 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0003_alter_paper_li_authors_alter_paper_li_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='paper',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='链接'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='时间'),
        ),
    ]
