# Generated by Django 4.0.3 on 2023-04-26 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0004_keywords_created_at_paper_created_at_paper_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
