# Generated by Django 4.0.3 on 2023-04-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0005_alter_paper_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='json_str',
            field=models.TextField(blank=True, null=True, verbose_name='原始json'),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='json_str',
            field=models.TextField(blank=True, null=True, verbose_name='原始json'),
        ),
    ]
