# Generated by Django 4.0.3 on 2023-05-04 09:00

from django.db import migrations, models
import science.models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0009_scholar_h_index_scholar_referenced_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='h_index',
            field=models.IntegerField(blank=True, default=science.models.gen_h_index, null=True, verbose_name='h指数'),
        ),
    ]
